[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://api.vapi.ai https://www.google-analytics.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://api.vapi.ai; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com https://api.vapi.ai wss://api.vapi.ai; frame-src 'self' https://www.youtube.com; media-src 'self' https://api.vapi.ai; worker-src 'self' blob:;"

[context.production.environment]
  NODE_ENV = "production"
  VAPI_API_KEY = "@vapi_api_key"
  VAPI_ASSISTANT_ID = "@vapi_assistant_id"
  EMAIL_USER = "@email_user"
  EMAIL_PASS = "@email_pass"
  EMAIL_TO = "@email_to" 